import type { NextPage } from "next";
import Head from "next/head";
import Header from "../components/Header";
import Profile from "../components/Profile";
import Works from "../components/Works";
import Work from "../components/Work";
import data from "../data.js";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Younggeun Jun</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Profile />
      <Works>
        {/* {data.map((item) => {
          return (
            <Work
              key={item.id}
              name={item.name}
              img={item.img}
              description={item.description}
              stacks={item.stacks}
              link={item.link}
            />
          );
        })} */}
      </Works>
    </div>
  );
};

export default Home;
